baseURL = "https://vicentin.xyz/"
languageCode = "en-us"
title = "Bom dia"
theme = "nightfall"


[params]
user = "felipe"
hostname = "vicentin.xyz"
sitedescription = 'Your website description'

[params.author]
name = "Felipe Scherer Vicentin"
email = "hello@vicentin.xyz"


[[params.social]]
key = 0
name = "GitHub"
url = "https://github.com/Vinschers"
icon = "fa-brands fa-github"         # Add link to your icon font to `layouts/partials/custom-head.html`
target = "_blank"                    # Defines your target option in a-href. _blank for a new Tab for example.
aria = "GitHub Profile"              # Define the aria label for accessibility like page reader - this is better for your SEO

[[params.social]]
key = 1
name = "Email"
icon = "fa-solid fa-envelope"
target = "_blank"
url = "mailto:hello@vicentin.xyz"


[menu]
[[menu.header]]
name = "posts"
weight = 0
url = "/posts"


[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]
