baseURL = 'https://vicentin.xyz/'
languageCode = 'en-us'
theme = "PaperMod"
enableEmoji = true
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
paginate = 5

[params]
displayFullLangName = true
showToc = true
showBreadCrumbs = true
ShowCodeCopyButtons = true
ShowPostNavLinks = false
ShowReadingTime = true
math = true


[outputs]
home = ["HTML", "RSS", "JSON"]

[languages]
[languages.en]
languageName = "English"
languageCode = "en"
title = "Scherer's blog"
[languages.en.params.homeInfoParams]
Title = "Bio"
Content = """
Name: Felipe Scherer Vicentin

[More](/cv)
"""
[[languages.en.menu.main]]
name = "CV"
url = "/cv"
weight = 1
[[languages.en.menu.main]]
name = "notes"
url = "/notes"
weight = 2
[[languages.en.menu.main]]
name = "search"
url = "/search"
weight = 3

[languages.pt]
languageName = "Português"
languageCode = "pt-BR"
title = "Blog do Scherer"
[languages.pt.params.homeInfoParams]
Title = "Bio"
Content = """
Nome: Felipe Scherer Vicentin

[Mais](/cv)
"""
[[languages.pt.menu.main]]
name = "CV"
url = "/cv"
weight = 1
[[languages.pt.menu.main]]
name = "anotações"
url = "notes"
weight = 2
[[languages.pt.menu.main]]
name = "pesquisar"
url = "/search"
weight = 3


[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
noClasses = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]
