baseURL = 'https://vicentin.xyz/'
languageCode = 'en-us'
title = "Scherer's blog"
theme = "PaperMod"
enableEmoji = true
pygmentsUseClasses = true
paginate = 5

mainsections = ["posts"]

[params]
displayFullLangName = true
ShowPostNavLinks = true
showToc = true
math = true

[menu]
[[menu.main]]
name = "Posts"
url = "/posts"

[[menu.main]]
name = "CV"
url = "/cv"

[[menu.main]]
name = "Search"
url = "/search"


[outputs]
home = ["HTML", "RSS", "JSON"]

[languages]
[languages.en]
languageName = "English"
languageCode = "en"
[languages.en.params.homeInfoParams]
Title = "Bio"
Content = """
Name: Felipe Scherer Vicentin

[More](/cv)
"""

[languages.pt]
languageName = "Português"
languageCode = "pt-BR"
[languages.pt.params.homeInfoParams]
Title = "Bio"
Content = """
Nome: Felipe Scherer Vicentin

[Mais](/cv)
"""

[languages.fr]
languageName = "Français"
languageCode = "fr"


[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]
